  name: 'Minimal Character Profile'
  description: 'Simple Character Profile Layout with minimal fields'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7917001.-f2u-minimal-chara-profile'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7917001?1597849483'