  name: 'Stats with Progressbars and Values'
  description: 'Use this Layout to generate standard progressbars with values for stats'
  style: 'background-color: #2a5a7e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7909215.-f2u-stats-with-pb-with-val-'
  type: 'codesnippet'