  name: 'Interstellar Dust'
  description: "Originally a custom for Swissy, this character profile theme has dark colours as a base. It has tabs and a moodboard section. 100% mobile responsive with lots and lots of slots for character information."
  style: 'background-color: #eee; color: #333'
  author: 'Circlejourney'
  author_link: 'https://toyhou.se/circlejourney'
  license: "100% free to use. You're allowed to edit them and frankenstein them with other code. Please don't remove credit, that is all I ask."
  link: 'https://toyhou.se/6191922.interstellar-dust'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/6191922?1583386454'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/75580.circlejourney-s-code-creations-free-'>Circlejourney's code freebies</a>"
  author_avatar: 'https://f2.toyhou.se/file/f2-toyhou-se/users/circlejourney'