  name: 'Character Profile without Tabs'
  description: 'Simple Basic Character Profile Layout without Tabs'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://toyhou.se/7916778.-f2u-character-profile'
  type: 'character'