  name: 'Relationships List with Status'
  description: 'Use this Layout to generate Relationships-List or Friends-List with rounded img, link and status'
  style: 'background-color: #2a5a7e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7909237.-f2u-relationships-list-2'
  type: 'codesnippet'