  name: 'Stats with Progressbars'
  description: 'Use this Layout to generate standard progressbars for stats'
  style: 'background-color: #2a5a7e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7909154.-f2u-stats-with-progressbars'
  type: 'codesnippet'