  name: 'Stats with Stars'
  description: 'Use this Layout to generate Stars as values for stats'
  style: 'background-color: #2a5a7e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7909163.-f2u-stats-with-stars'
  type: 'codesnippet'