  name: 'simple profile card'
  description: "Hello! This is a F2U profile code. It's responsive, and you're free to do what you'd like with it as long as you maintain credit!"
  style: 'background-color: #3a3639; color: #fcfbf6'
  author: 'snail-legs'
  author_link: 'https://toyhou.se/snail-legs'
  license: "Keep the code credit intact. <a href='https://toyhou.se/~forums/16.htmlcss-graphics/139364.the-snail-s-shell-html-codes'>For more information, please visit [the snail's shell]</a>"
  link: 'https://toyhou.se/6839883.layout-simple-profile-card'
  type: 'user'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/6839883?1592936183'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/139364.the-snail-s-shell-html-codes'>The Snail's Shell | HTML codes</a>"