  name: 'User Profile with Art'
  description: 'User Profile Layout with Status and Gallery'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7931345.-f2u-user-profile-with-art'
  type: 'user'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7931345?1597869858'