  name: 'Full Config'
  description: 'Test Character Preview with Rich Config'
  style: 'background-color: #2a5a7e; color: #f7fd95'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://github.com/furudbat/thhg/tree/master/templates/zz_character_fullconfig'
  disable: true