  name: 'Simple Layout with Tabs'
  description: 'Simple Basic Character Profile Layout with Tabs'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://github.com/furudbat/thhg/tree/master/templates'
  type: 'character'