  name: 'User Axis'
  description: 'More F2U Themes by Eggy -> https://toyhou.se/Eggy/characters/folder:268984'
  style: 'background-color: #f8b526; color: #070707'
  author: '<i class="fas fa-skull user-name-icon"></i>Eggy'
  author_link: 'https://toyhou.se/Eggy'
  license: 'Read the rules before using ! -> https://toyhou.se/~bulletins/40160.freebie-rules'
  link: 'https://toyhou.se/6742833.-freebie-user-axis'
  type: 'user'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/6742833?1588169704'