  name: 'Split Boxes'
  description: "A simple character profile with the information split across the container."
  style: 'background-color: #fff; color:#1e1e1e;'
  author: 'Zodia'
  author_link: 'https://toyhou.se/Zodia'
  license: '<a href="https://toyhou.se/~bulletins/95096.code-rules">Please remember to read the rules before using!!</a>'
  link: 'https://toyhou.se/4432122.-f2u-01-split-boxes'
  type: 'character'
  preview: 'https://file.toyhou.se/characters/4432122?1562018377'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/108777.-zodia-s-html-codes'>Zodia's HTML Codes</a>"
  author_avatar: 'https://file.toyhou.se/users/Zodia'