  name: 'Scale'
  description: 'More F2U Themes by Eggy -> https://toyhou.se/Eggy/characters/folder:268984'
  style: 'background-color: #f8b526; color: #070707'
  author: '<i class="fas fa-skull user-name-icon"></i>Eggy'
  author_link: 'https://toyhou.se/Eggy'
  license: 'Read the rules before using ! -> https://toyhou.se/~bulletins/40160.freebie-rules'
  link: 'https://toyhou.se/5662687.-freebie-scale'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/5662687?1577475276'