  name: 'User - In A Nutshell'
  description: "Originally a custom for Historia. This user profile theme displays a lot of text in a digestible way. It includes a space for a banner, a user icon, social media, notes and a list of projects. Mobile responsive, organises profile into main area and sidebar."
  style: 'background-color: #eee; color: #333'
  author: 'Circlejourney'
  author_link: 'https://toyhou.se/circlejourney'
  license: "100% free to use. You're allowed to edit them and frankenstein them with other code. Please don't remove credit, that is all I ask."
  link: 'https://toyhou.se/6351798.in-a-nutshell'
  type: 'character'