  name: 'Super Special Double Deluxe'
  description: "A custom for reinapepiada, this theme is designed to contain lots and lots of text in multiple sections, and has slots for quote, stats, music themes, and a moodboard."
  style: 'background-color: #eee; color: #333'
  author: 'Circlejourney'
  author_link: 'https://toyhou.se/circlejourney'
  license: "100% free to use. You're allowed to edit them and frankenstein them with other code. Please don't remove credit, that is all I ask."
  link: 'https://toyhou.se/6388687.super-special-double-deluxe'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/6388687?1585115598'