  name: 'Character Profile with Tabs'
  description: 'Simple Basic Character Profile Layout with Tabs'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://toyhou.se/7909361.-f2u-chara-profile-with-tabs'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7909361?1597848953'