  name: 'Simplified Profile'
  description: "A simplified character profile made as a request for a friend! Has custom color support!"
  style: 'background-color: #fff; color:#1e1e1e;'
  author: 'Zodia'
  author_link: 'https://toyhou.se/Zodia'
  license: '<a href="https://toyhou.se/~bulletins/95096.code-rules">Please remember to read the rules before using!!</a>'
  link: 'https://toyhou.se/6545040.-f2u-07-simplified'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/6545040?1586556611'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/108777.-zodia-s-html-codes'>Zodia's HTML Codes</a>"
  author_avatar: 'https://file.toyhou.se/users/Zodia'