  name: 'Aesthetic Card (Light)'
  description: "A small user profile with an aesthetic image background. Background can be changed to any image you'd like!"
  style: 'background-color: #fff; color:#1e1e1e;'
  author: 'Zodia'
  author_link: 'https://toyhou.se/Zodia'
  license: '<a href="https://toyhou.se/~bulletins/95096.code-rules">Please remember to read the rules before using!!</a>'
  link: 'https://toyhou.se/4439093.-f2u-02-aesthetic-card'
  type: 'user'
  preview: 'https://file.toyhou.se/characters/4439093?1562121670'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/108777.-zodia-s-html-codes'>Zodia's HTML Codes</a>"
  author_avatar: 'https://file.toyhou.se/users/Zodia'