  name: 'Minimal Card'
  description: 'Minimal Card User Profile Layout'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://toyhou.se/7909374.-f2u-simple-user-profile-card'
  type: 'user'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7909374?1597849808'