  name: 'Minimal Card'
  description: 'Minimal Card Character Profile Layout'
  style: 'background-color: #1190FF; color: #DDDDFF'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'free to use and modify'
  link: 'https://toyhou.se/FurudBat'