  name: 'List'
  description: 'Use this Layout to generate a simple list with icons'
  style: 'background-color: #2a5a7e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify.'
  link: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7909096?1597701920'
  type: 'codesnippet'