  name: 'User Template - Handlebars'
  description: 'Minimal User Template to copy and use as a blueprint, use handlebars as template engine'
  style: 'background-color: #E74C3C; color: #ffffff'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://github.com/furudbat/stikflat/tree/master/templates'
  type: 'template'
  