  name: 'Basic with Tabs'
  description: 'Simple Basic Character Profile Layout with Tabs'
  style: 'background-color: #0080FF; color: #CCCCFF'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'free to use and modify'
  link: 'https://toyhou.se/FurudBat'