  name: 'Softie Agenda'
  description: "Custom for needlegutz || Made F2U for all users! - custom accent color!"
  style: 'background-color: #acdbdf; color: #383838;'
  author: 'BunBox'
  author_link: 'https://toyhou.se/BunBox'
  license: >-
    - please do not remove credit! <br/>
    - please dont sell/resell this code for its F2U <br/>
    - Feel free to make as much edits to it as you like! <br/>
    - Please comment under the designated forum or code post that you are using it! I'd love to see what you do with it <v>
  link: 'https://toyhou.se/7278749.softie-agenda'
  type: 'user'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7278749?1592509076'
  more: "<a href='https://toyhou.se/~forums/16.htmlcss-graphics/139882.-bunbox-codes-f2u-p2u-html-4-20-'>BunBox Codes</a>"
  author_avatar: 'https://f2.toyhou.se/file/f2-toyhou-se/users/BunBox'