  name: 'Minimal Character Layout'
  description: 'Simple Basic Character Profile Layout with minimal fields'
  style: 'background-color: #1a4a6e; color: #f7fdf5'
  author: 'furudbat'
  author_link: 'https://toyhou.se/FurudBat'
  license: 'Free to use and modify'
  link: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7917001?1597765208'
  type: 'character'