  name: 'side by side'
  description: "Hello! This is a F2U profile code with room for a bit of written info and a featured image. It's responsive, and you're free to do what you'd like with it as long as you maintain credit!"
  style: 'background-color: #3a3639; color: #fcfbf6'
  author: 'snail-legs'
  author_link: 'https://toyhou.se/snail-legs'
  license: "For more information, please visit [the snail's shell] -> https://toyhou.se/~forums/16.htmlcss-graphics/139364.the-snail-s-shell-html-codes"
  link: 'https://toyhou.se/7689827.layout-side-by-side'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7689827?1596293985'