  name: 'Character - journal'
  description: "Hello! This is a F2U profile code meant to work as a journal-type page for your oc! It's got a page for basic info and two pages for journal entries, although it shouldn't be too hard to add more of those. There's also space for a pagedoll/other graphic- I'd reccomend using a portait image for the best effect. It's responsive, and you're free to do what you'd like with it as long as you maintain credit!"
  style: 'background-color: #3a3639; color: #fcfbf6'
  author: 'snail-legs'
  author_link: 'https://toyhou.se/snail-legs'
  license: "For more information, please visit [the snail's shell] -> https://toyhou.se/~forums/16.htmlcss-graphics/139364.the-snail-s-shell-html-codes"
  link: 'https://toyhou.se/7497816.layout-journal'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/7497816?1594383763'