  name: 'Open - Grid Version'
  description: 'Character profiles. Can be used by all users.'
  style: 'background-color: #f8b526; color: #070707'
  author: '<i class="fas fa-skull user-name-icon"></i>Eggy'
  author_link: 'https://toyhou.se/Eggy'
  license: '<a href="https://toyhou.se/~bulletins/40160.freebie-rules">Read the rules before using any freebies!</a>'
  link: 'https://toyhou.se/4556624.-freebie-open'
  type: 'character'
  preview: 'https://f2.toyhou.se/file/f2-toyhou-se/characters/4556624?1591832733'
  more: '<a href="https://toyhou.se/~forums/16.htmlcss-graphics/16520.-eggy-html-css">Eggy HTML & CSS</a>'
  author_avatar: 'https://f2.toyhou.se/file/f2-toyhou-se/users/Eggy'